apiVersion: skaffold/v4beta1
kind: Config
metadata:
  name: ticketing-microservices
build:
  googleCloudBuild: #esta conf es para que funcione en el contexto del cluster de GCP
    projectId: ticketing-microservices-369119
  artifacts:
    - image: us.gcr.io/ticketing-microservices-369119/auth # este es el nombre necesario para que encuentre la imagen correcta
      context: auth
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - dest: .
            src: "src/**/*.ts"
    - image: us.gcr.io/ticketing-microservices-369119/payment
      context: payment
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - dest: .
            src: "src/**/*.ts"
manifests:
  rawYaml:
    - infra/k8s/auth/auth-deployment.yaml
    - infra/k8s/auth/auth-mongodb-deployment.yaml
    - infra/k8s/payment/payment-deployment.yaml

    - infra/k8s/ingress-load-balancer.yaml

    - infra/k8s/auth/auth-services-ip-cluster.yaml
    - infra/k8s/auth/auth-mongodb-services-ip-cluster.yaml
    - infra/k8s/payment/payment-services-ip-cluster.yaml
