apiVersion: skaffold/v2beta17
kind: Config
deploy:
  kubectl:
    manifests:
      - ./infra/k8s/*
build:
  local:
    push: false
  artifacts:
    - image: yasniel1408/auth
      context: auth
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - dest: .
            src: "src/**/*.ts"
    - image: yasniel1408/payment
      context: payment
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - dest: .
            src: "*src/**/*.ts"
