apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - name: auth
          image: "us.gcr.io/ticketing-microservices-369119/auth:latest"
          resources:
            limits:
              cpu: 1000m
              memory: 800Mi
            requests:
              cpu: 300m
              memory: 500Mi
