apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment
  template:
    metadata:
      labels:
        app: payment
    spec:
      containers:
        - name: payment
          image: "us.gcr.io/ticketing-microservices-369119/payment:latest"
          resources:
            limits:
              cpu: 1000m
              memory: 800Mi
            requests:
              cpu: 300m
              memory: 350Mi
