apiVersion: v1
kind: Service
metadata:
  name: nats-ui-service
spec:
  selector:
    app: nats-ui
  type: ClusterIP
  ports:
    - name: nats-ui
      protocol: TCP
      port: 8282
      targetPort: 8282
