apiVersion: apps/v1
kind: Deployment
metadata:
  name: nats-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nats
  template:
    metadata:
      labels:
        app: nats
    spec:
      containers:
        - name: nats
          image: "nats-streaming:latest"
          args:
            [
              "-p",
              "4222",
              "-m",
              "8222",
              "-hbi", # Frecuencia con la que un servidor va a realizar solicitudes a sus clientes
              "5s",
              "-hbt", # En cuento tiempo debe responder cada cliente
              "5s",
              "-hbf", # Cantidad de veces que un cliente puede fallar antes de que NATS Server asuma que esa conexion esta muerta
              "2",
              "-SD",
              "-cid",
              "ticketing",
            ]
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "800m"
