apiVersion: v1
kind: Service
metadata:
  name: orders-mongodb-service
spec:
  selector:
    app: orders-mongodb
  type: ClusterIP
  ports:
    - name: orders-mongodb
      protocol: TCP
      port: 27017
      targetPort: 27017
