apiVersion: apps/v1
kind: Deployment
metadata:
  name: orders-mongodb-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orders-mongodb
  template:
    metadata:
      labels:
        app: orders-mongodb
    spec:
      containers:
        - name: orders-mongodb
          image: "mongo:latest"
