apiVersion: v1
kind: Service
metadata:
  name: payments-mongodb-service
spec:
  selector:
    app: payments-mongodb
  type: ClusterIP
  ports:
    - name: payments-mongodb
      protocol: TCP
      port: 27017
      targetPort: 27017
