apiVersion: apps/v1
kind: Deployment
metadata:
  name: payments-mongodb-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payments-mongodb
  template:
    metadata:
      labels:
        app: payments-mongodb
    spec:
      containers:
        - name: payments-mongodb
          image: "mongo:latest"
