apiVersion: v1
kind: Service
metadata:
  name: payments-service
spec:
  selector:
    app: payments
  type: ClusterIP
  ports:
    - name: payments
      protocol: TCP
      port: 3000
      targetPort: 3000
