apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-mongodb-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-mongodb
  template:
    metadata:
      labels:
        app: auth-mongodb
    spec:
      containers:
        - name: auth-mongodb
          image: "mongo:latest"
